name: Set up vim on Ubuntu
on:
  pull_request:
    branches: ['main']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ubuntu-setup:
    name: Set up Vim on Ubuntu
    runs-on: ubuntu-20.04
    timeout-minutes: 60

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up Vim
        run: ./install.sh
